apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o k8s.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      app: wp-veritas
      version: 0.0.1
    name: wp-veritas
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 3000
    selector:
      app: wp-veritas
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o k8s.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      app: mongo
    name: mongo
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: mongo
      spec:
        containers:
        - args:
          - mongod
          - --storageEngine=wiredTiger
          image: mongo:latest
          name: mongo
          resources: {}
        restartPolicy: Always
  status: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.cmd: kompose convert -f docker-compose.yml -o k8s.yml
      kompose.version: 1.17.0 (a74acad)
    creationTimestamp: null
    labels:
      app: wp-veritas
    name: wp-veritas
  spec:
    replicas: 1
    strategy: {}
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: wp-veritas
      spec:
        containers:
        - env:
          - name: METEOR_SETTINGS
            value: |-
              {
                "accred": {
                  "password": "n2utoqeltum1"
                }
              }
          - name: MONGO_URL
            value: mongodb://mongo:27017/meteor
          - name: ROOT_URL
            value: http://localhost
          image: epflidevelop/wp-veritas
          name: wp-veritas
          ports:
          - containerPort: 3000
          resources: {}
        restartPolicy: Always
  status: {}
kind: List
metadata: {}

