- name: wp-veritas secrets
  openshift:
    state: latest
    resource: Secret
    name: "{{ wp_veritas_secret_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      stringData:
        mongo-url: 'mongo-url: mongodb://{{wp_veritas_db_user | eyaml}}:{{wp_veritas_db_password | eyaml}}@{{wp_veritas_db_host}}/{{wp_veritas_db_name}}'
      kind: Secret
      metadata:
        name: "{{ wp_veritas_secret_name }}"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
