- name: wp-veritas secrets
  openshift:
    state: latest
    resource: Secret
    name: "{{ wp_veritas_secret_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      stringData:
        mongo-url: 'mongodb://{{ wp_veritas_db_user }}:{{ wp_veritas_db_password }}@mongodb-svc-1.epfl.ch/{{ wp_veritas_db_name }}'
      kind: Secret
      metadata:
        name: "{{ wp_veritas_secret_name }}"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
