- name: wp-veritas secrets
  openshift:
    state: latest
    resource: Secret
    name: "{{ wp_veritas_secret_name }}"
    namespace: "{{ openshift_namespace }}"
    content: |
      apiVersion: v1
      stringData:
        mongo-url: 'mongodb://{{ wp_veritas_db_user }}:{{ wp_veritas_db_password }}@{{ db_host }}.epfl.ch/{{ wp_veritas_db_name }}'
        meteor-settings: '{{ lookup("env", "METEOR_SETTINGS") }}' # MOVE this to KEYBASE
        bot-token: '{{ wp_veritas_bot_token }}'
        alert-telegram-ids: '{{ wp_veritas_alerts_telegram_ids }}'
      kind: Secret
      metadata:
        name: "{{ wp_veritas_secret_name }}"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
